# Generated by Django 5.0.7 on 2024-08-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_room_options_room_paraticipants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("-updated", "-created")},
        ),
        migrations.RenameField(
            model_name="room",
            old_name="paraticipants",
            new_name="participants",
        ),
    ]
